server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          skip-ssl-validation: true
#          to attach config server to github
          uri: https://github.com/vivekbinjola/config-files
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          searchPaths: petclinic


