server:
  port: 8010
  servlet:
    context-path: /pets
spring:
  application:
    name: pet-service
  config:
    import=optional:configserver: http://localhost:8888/pet/service


  cloud:
    config:
      enabled: false

  datasource:
    hikari:
      maximum-pool-size: 2
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}

message: "hello from github"



